#!/usr/bin/env python3
"""gif-factory — 플레이 녹화 영상에서 홍보용 GIF 후보를 자동으로 뽑는다.

    gif_factory.py                      # config.env / 환경변수의 INBOX 를 훑어 새 영상 처리
    gif_factory.py --file 녹화.mp4      # 파일 하나만 (테스트용)
    gif_factory.py --no-claude          # 움직임 점수만으로 선정 (claude CLI 없이)

흐름: 영상 → 움직임 점수(ffmpeg scene score) → 후보 창 N개 → 프레임 시트 →
      claude -p 가 시트를 보고 3개 선정 + 문구 초안 (없으면 점수 상위) → GIF 2크기 + mp4 →
      OUTBOX/<날짜>/<영상이름>/ + SUMMARY.md → (gh 있으면) 티켓 댓글.

의존: python3 (3.9+), ffmpeg. 선택: claude CLI, gh CLI.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
VIDEO_EXT = {".mp4", ".mkv", ".mov", ".avi", ".webm", ".m4v"}
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


# ---------- 설정 ----------

def load_env_file(path: pathlib.Path) -> None:
    """KEY=VALUE 파일을 환경변수로. 이미 있는 키는 건드리지 않는다."""
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k, v = k.strip(), v.strip().strip('"').strip("'")
        os.environ.setdefault(k, os.path.expanduser(v))


def parse_args(argv: list[str]) -> argparse.Namespace:
    load_env_file(HERE / "config.env")
    env = os.environ.get
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--inbox", default=env("GIF_INBOX", ""), help="녹화 영상이 들어오는 폴더")
    p.add_argument("--outbox", default=env("GIF_OUTBOX", ""), help="결과가 나가는 폴더")
    p.add_argument("--file", help="폴더 대신 이 영상 하나만 처리")
    p.add_argument("--clip-len", type=float, default=float(env("GIF_CLIP_LEN", "6")), help="클립 길이(초)")
    p.add_argument("--candidates", type=int, default=int(env("GIF_CANDIDATES", "8")), help="후보 창 개수")
    p.add_argument("--picks", type=int, default=int(env("GIF_PICKS", "3")), help="최종 선정 개수")
    p.add_argument("--widths", default=env("GIF_WIDTHS", "480,320"), help="GIF 가로 크기들 (쉼표)")
    p.add_argument("--fps", type=int, default=int(env("GIF_FPS", "15")), help="GIF 프레임레이트")
    p.add_argument("--scale", default=env("GIF_SCALE", "neighbor"), help="ffmpeg scale flags. 픽셀아트=neighbor, 일반=lanczos")
    p.add_argument("--no-claude", action="store_true", default=env("GIF_NO_CLAUDE", "") == "1", help="claude 선정 생략")
    p.add_argument("--issue", default=env("GIF_ISSUE", ""), help="결과 댓글을 남길 GitHub 이슈 번호")
    p.add_argument("--repo", default=env("GIF_REPO", ""), help="owner/repo (gh 댓글용)")
    p.add_argument("--min-age", type=int, default=int(env("GIF_MIN_AGE", "90")), help="이 초보다 젊은 파일은 아직 동기화 중으로 보고 건너뜀")
    p.add_argument("--force", action="store_true", help="이미 처리한 파일도 다시")
    a = p.parse_args(argv)
    if not a.file and not a.inbox:
        p.error("--inbox 또는 --file 이 필요합니다 (config.env 의 GIF_INBOX)")
    if not a.outbox:
        p.error("--outbox 가 필요합니다 (config.env 의 GIF_OUTBOX)")
    a.widths = [int(w) for w in str(a.widths).split(",") if w.strip()]
    return a


# ---------- ffmpeg ----------

def ffmpeg_bin() -> str:
    for cand in (os.environ.get("FFMPEG"), "ffmpeg", "/opt/homebrew/bin/ffmpeg", "/usr/local/bin/ffmpeg"):
        if cand and shutil.which(cand):
            return shutil.which(cand)
    try:  # pip install imageio-ffmpeg 로 받은 바이너리도 허용
        import imageio_ffmpeg  # type: ignore
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        pass
    sys.exit("ffmpeg 를 찾을 수 없습니다. brew install ffmpeg")


FFMPEG = None


def run(cmd: list[str], timeout: int = 600) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)


def motion_profile(video: pathlib.Path) -> list[tuple[float, float]]:
    """(시각, 장면변화점수) 목록. 점수가 클수록 화면이 많이 움직인 순간."""
    vf = "fps=10,scale=160:-2,select='gte(scene,0)',metadata=print:file=-"
    r = run([FFMPEG, "-hide_banner", "-nostats", "-i", str(video), "-vf", vf, "-an", "-f", "null", "-"])
    if r.returncode != 0:
        raise RuntimeError(f"ffmpeg 분석 실패: {r.stderr[-800:]}")
    out, t = [], None
    for line in r.stdout.splitlines():
        m = re.search(r"pts_time:([\d.]+)", line)
        if m:
            t = float(m.group(1))
            continue
        m = re.search(r"lavfi\.scene_score=([\d.]+)", line)
        if m and t is not None:
            out.append((t, float(m.group(1))))
    if not out:
        raise RuntimeError("움직임 점수를 얻지 못했습니다 (영상이 너무 짧거나 손상)")
    return out


def window_score(vals: list[float]) -> float:
    """창 점수 = 중앙값(꾸준한 움직임) - 씬 전환 페널티. 평균 대신 중앙값이라 컷 한 방의 스파이크에 안 끌려간다."""
    s = sorted(vals)
    median = s[len(s) // 2]
    cuts = sum(1 for v in vals if v > 0.5)   # 메뉴↔플레이 전환 같은 하드컷
    return median - 0.1 * cuts


def pick_windows(profile: list[tuple[float, float]], clip_len: float, n: int) -> list[dict]:
    """길이 clip_len 의 창을 1초 간격으로 훑어 점수 높은 순으로, 절반 이상 겹치는 창은 버린다."""
    duration = profile[-1][0]
    if duration <= clip_len:
        return [{"start": 0.0, "score": window_score([s for _, s in profile])}]
    windows = []
    t = 0.0
    while t + clip_len <= duration + 1e-6:
        vals = [s for (ts, s) in profile if t <= ts < t + clip_len]
        if vals:
            windows.append({"start": round(t, 2), "score": window_score(vals)})
        t += 1.0
    windows.sort(key=lambda w: w["score"], reverse=True)
    chosen: list[dict] = []
    for w in windows:
        if all(abs(w["start"] - c["start"]) >= clip_len * 0.5 for c in chosen):
            chosen.append(w)
        if len(chosen) >= n:
            break
    return chosen


def contact_sheet(video: pathlib.Path, start: float, clip_len: float, out: pathlib.Path) -> None:
    frames = 6
    vf = f"fps={frames}/{clip_len},scale=240:-2:flags=neighbor,tile={frames}x1"
    r = run([FFMPEG, "-hide_banner", "-loglevel", "error", "-y", "-ss", f"{start:.2f}", "-t", f"{clip_len:.2f}",
             "-i", str(video), "-vf", vf, "-frames:v", "1", "-q:v", "4", str(out)])
    if r.returncode != 0:
        raise RuntimeError(f"프레임 시트 실패: {r.stderr[-400:]}")


def render_gif(video: pathlib.Path, start: float, clip_len: float, width: int, fps: int, scale: str, out: pathlib.Path) -> None:
    graph = (f"fps={fps},scale={width}:-2:flags={scale},split[a][b];"
             f"[a]palettegen=max_colors=128:stats_mode=diff[p];"
             f"[b][p]paletteuse=dither=none:diff_mode=rectangle")
    r = run([FFMPEG, "-hide_banner", "-loglevel", "error", "-y", "-ss", f"{start:.2f}", "-t", f"{clip_len:.2f}",
             "-i", str(video), "-filter_complex", graph, "-loop", "0", str(out)])
    if r.returncode != 0:
        raise RuntimeError(f"GIF 실패: {r.stderr[-400:]}")


def render_mp4(video: pathlib.Path, start: float, clip_len: float, width: int, scale: str, out: pathlib.Path) -> None:
    vf = f"scale={width}:-2:flags={scale},scale=trunc(iw/2)*2:trunc(ih/2)*2,format=yuv420p"
    r = run([FFMPEG, "-hide_banner", "-loglevel", "error", "-y", "-ss", f"{start:.2f}", "-t", f"{clip_len:.2f}",
             "-i", str(video), "-vf", vf, "-an", "-c:v", "libx264", "-crf", "20", "-preset", "veryfast",
             "-movflags", "+faststart", str(out)])
    if r.returncode != 0:
        raise RuntimeError(f"mp4 실패: {r.stderr[-400:]}")


# ---------- 선정 ----------

def heuristic_picks(cands: list[dict], n: int) -> list[dict]:
    return [{"id": c["id"], "reason": "움직임 점수 상위", "captions": []} for c in cands[:n]]


def claude_picks(cands: list[dict], n: int, video_name: str) -> list[dict] | None:
    claude = shutil.which("claude")
    if not claude:
        print("  claude CLI 없음 → 점수 순으로 선정")
        return None
    template = (HERE / "prompt.md").read_text(encoding="utf-8")
    table = "\n".join(f"- 후보 {c['id']}: 시작 {c['start']}초, 움직임 {c['score']:.3f}, 시트 {c['sheet']}" for c in cands)
    prompt = template.replace("{{N}}", str(n)).replace("{{VIDEO}}", video_name).replace("{{CANDIDATES}}", table)
    try:
        r = subprocess.run([claude, "-p", prompt, "--allowedTools", "Read", "--output-format", "text"],
                           stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=420)
    except Exception as e:  # noqa: BLE001
        print(f"  claude 실행 실패 → 점수 순: {e}")
        return None
    m = re.search(r"\{[\s\S]*\"picks\"[\s\S]*\}", r.stdout)
    if r.returncode != 0 or not m:
        print(f"  claude 응답 해석 실패 → 점수 순: {(r.stderr or r.stdout)[-300:]}")
        return None
    try:
        data = json.loads(m.group(0))
        if data.get("note"):
            print(f"  claude 메모: {data['note']}")
        picks = data.get("picks", [])
        valid = {c["id"] for c in cands}
        picks = [p for p in picks if int(p.get("id", -1)) in valid][:n]
        if not picks:
            print("  claude 가 고를 만한 후보가 없다고 함 → 점수 순")
        return picks or None
    except Exception as e:  # noqa: BLE001
        print(f"  claude JSON 파싱 실패 → 점수 순: {e}")
        return None


# ---------- 처리 ----------

def human_size(n: int) -> str:
    return f"{n / 1024 / 1024:.1f}MB" if n >= 1024 * 1024 else f"{n // 1024}KB"


def process(video: pathlib.Path, a: argparse.Namespace) -> pathlib.Path:
    day = dt.datetime.now().strftime("%Y-%m-%d")
    out_dir = pathlib.Path(a.outbox) / day / video.stem
    work = out_dir / "sheets"
    work.mkdir(parents=True, exist_ok=True)
    print(f"[{video.name}] 분석 중")
    profile = motion_profile(video)
    windows = pick_windows(profile, a.clip_len, a.candidates)
    cands = []
    for i, w in enumerate(windows, 1):
        sheet = work / f"cand{i:02d}.jpg"
        contact_sheet(video, w["start"], a.clip_len, sheet)
        cands.append({"id": i, "start": w["start"], "score": w["score"], "sheet": str(sheet)})
    print(f"  후보 {len(cands)}개, 영상 길이 {profile[-1][0]:.0f}초")

    picks = None if a.no_claude else claude_picks(cands, a.picks, video.name)
    picker = "claude" if picks else "움직임 점수"
    picks = picks or heuristic_picks(cands, a.picks)

    rows = []
    for rank, p in enumerate(picks, 1):
        c = next(x for x in cands if x["id"] == int(p["id"]))
        files = []
        for w in a.widths:
            g = out_dir / f"clip{rank}_{w}.gif"
            render_gif(video, c["start"], a.clip_len, w, a.fps, a.scale, g)
            files.append(g)
        m = out_dir / f"clip{rank}.mp4"
        render_mp4(video, c["start"], a.clip_len, max(a.widths), a.scale, m)
        files.append(m)
        rows.append({"rank": rank, "start": c["start"], "reason": p.get("reason", ""),
                     "captions": p.get("captions", []), "files": files, "sheet": c["sheet"]})
        print(f"  clip{rank}: {c['start']}초~ ({', '.join(f'{f.name} {human_size(f.stat().st_size)}' for f in files)})")

    summary = write_summary(out_dir, video, rows, picker, a)
    comment_issue(summary, video, rows, a)
    return out_dir


def write_summary(out_dir: pathlib.Path, video: pathlib.Path, rows: list[dict], picker: str, a: argparse.Namespace) -> str:
    lines = [f"# {video.name} → GIF 후보 {len(rows)}개", "",
             f"선정: {picker} · 클립 {a.clip_len:.0f}초 · {dt.datetime.now().strftime('%Y-%m-%d %H:%M')}", ""]
    for r in rows:
        lines.append(f"## clip{r['rank']} — {r['start']}초부터")
        if r["reason"]:
            lines.append(f"- 고른 이유: {r['reason']}")
        lines.append("- 파일: " + ", ".join(f"`{f.name}` ({human_size(f.stat().st_size)})" for f in r["files"]))
        if r["captions"]:
            lines.append("- 문구 초안:")
            lines += [f"  {i}. {c}" for i, c in enumerate(r["captions"], 1)]
        lines.append("")
    first = rows[0] if rows else None
    if first and first["captions"]:
        lines += ["## 첫 글 템플릿 (골라서 고쳐 쓰기)", "",
                  "```", first["captions"][0], "",
                  "(만드는 게임 한 줄) · (지금 어디까지인지 한 줄)", "질문 하나: ", "```", ""]
    text = "\n".join(lines)
    (out_dir / "SUMMARY.md").write_text(text, encoding="utf-8")
    return text


def comment_issue(summary: str, video: pathlib.Path, rows: list[dict], a: argparse.Namespace) -> None:
    if not a.issue:
        return
    gh = shutil.which("gh")
    if not gh:
        print("  gh 없음 → 티켓 댓글 생략 (SUMMARY.md 는 남김)")
        return
    body = summary.replace("# ", "### ", 1) + f"\n\n결과 폴더: `{a.outbox}/…/{video.stem}/`" + FOOTER
    cmd = [gh, "issue", "comment", str(a.issue), "--body", body]
    if a.repo:
        cmd += ["--repo", a.repo]
    r = run(cmd, timeout=60)
    print("  티켓 댓글 남김" if r.returncode == 0 else f"  티켓 댓글 실패: {r.stderr[-200:]}")


def state_path(a: argparse.Namespace) -> pathlib.Path:
    return pathlib.Path(a.outbox) / ".processed.json"


def load_state(a: argparse.Namespace) -> dict:
    p = state_path(a)
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def save_state(a: argparse.Namespace, st: dict) -> None:
    state_path(a).parent.mkdir(parents=True, exist_ok=True)
    state_path(a).write_text(json.dumps(st, ensure_ascii=False, indent=1), encoding="utf-8")


def pending_videos(a: argparse.Namespace, st: dict) -> list[pathlib.Path]:
    inbox = pathlib.Path(a.inbox)
    if not inbox.is_dir():
        sys.exit(f"INBOX 폴더가 없습니다: {inbox}")
    out = []
    now = time.time()
    for f in sorted(inbox.iterdir()):
        if f.suffix.lower() not in VIDEO_EXT or f.name.startswith("."):
            continue
        key = f"{f.name}:{f.stat().st_size}"
        if key in st and not a.force:
            continue
        if now - f.stat().st_mtime < a.min_age:
            print(f"[{f.name}] 아직 동기화 중일 수 있어 다음 번에 (수정 {int(now - f.stat().st_mtime)}초 전)")
            continue
        out.append(f)
    return out


def main(argv: list[str]) -> int:
    global FFMPEG
    a = parse_args(argv)
    FFMPEG = ffmpeg_bin()
    if a.file:
        process(pathlib.Path(a.file).expanduser().resolve(), a)
        return 0
    st = load_state(a)
    videos = pending_videos(a, st)
    if not videos:
        print("새 영상 없음")
        return 0
    failed = 0
    for v in videos:
        try:
            out = process(v, a)
            st[f"{v.name}:{v.stat().st_size}"] = {"done": dt.datetime.now().isoformat(timespec="seconds"), "out": str(out)}
            save_state(a, st)
        except Exception as e:  # noqa: BLE001
            failed += 1
            print(f"[{v.name}] 실패: {e}", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
